### ISSUE TITLE
No need the wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [sparkfun/Si4703_FM_Tuner_Evaluation_Board#10]
The line `while(Wire.available() < 32) ;` after the Wire.requestFrom() can be removed in:
- Si4703_FM_Tuner_Evaluation_Board/Firmware/Si4703_Example/Si4703_Example.ino
- Si4703_FM_Tuner_Evaluation_Board/Libraries/Arduino/src/SparkFunSi4703.cpp

When the Wire.requestFrom() returns, the I2C transaction on the bus has completely finished and the received data is waiting in a buffer in the Wire library. There is no need to wait for something.

**Comment by Grahldg** [comment]
Hi @Koepel ,

I removed both instances as well as one in the [Arduino Library](https://github.com/sparkfun/SparkFun_Si4703_Arduino_Library).
