### ISSUE TITLE
Read/Write registers hanging?

### ISSUE THREAD

**Issue by pencerw** [sparkfun/Si4703_FM_Tuner_Evaluation_Board#5]
Having issues getting this project working. I'm currently working on the evaluation board + an Uno (photo attached).

![img_9646](https://f.cloud.github.com/assets/3917864/1730412/e26b73c2-62de-11e3-94e7-255cd9fdfef4.jpeg)

"Si4703_Example.ino" compiles and loads onto the Uno fine. After programming, I open a serial monitor and reset the Uno, and the serial monitor says "Initializing I2C and Si4703" and then hangs indefinitely. Screenshot attached. I can confirm with my multimeter that the eval board is getting 3.3v, but I hear nothing - no amplifier pop or anything - out of the headphones. 

![screen shot 2013-12-11 at 2 31 30 pm](https://f.cloud.github.com/assets/3917864/1730418/10387dd6-62df-11e3-92b6-76ed898952bb.png)

I spent a little while adding some debugging code and isolated the problem at the register read/write cycle. Second screenshot attached.

![screen shot 2013-12-11 at 3 19 25 pm](https://f.cloud.github.com/assets/3917864/1730422/15ee7456-62df-11e3-95a0-2f9cf518f6f9.png)

Then I spent some time with the "Si4703_Radio_Test" sketch. It also compiles & loads without errors, but hangs on radio.powerOn(). I added debugging comments to this too:
![screen shot 2013-12-11 at 10 47 08 pm](https://f.cloud.github.com/assets/3917864/1730451/64ea5736-62e0-11e3-91e6-dcff93727522.png)

At this point I'm a bit over my head, but I'm wondering if it's an issue with an updated version of the chip... I'm aware that the older libraries were written to earlier editions of AN230 (0.61, I believe) and 0.9 is now available... but like I said, I'm a bit over my head here :)

Happy to provide more details, photos, etc - just let me know!

Spencer

**Comment by andmarti1424** [comment]
Hello. I am having a similar problem too. I think my Si4703 chip could be burnt. Just to try.. I only connect the 3.3V and GND wires from my uno to the si4703 chip, and after a couple of seconds, it hangs the UNO. Did you have this kind of problem?  Thanks!

**Comment by gbatalski** [comment]
Sorry for the stupid question, but your setup shows only USB, UNO and SI4703 board. Do you mean, this setup is not a correct one (i don't see any ftdi)? I have the same problem: Nano + Si4703 (vcc on 3.3V) = hang up on powerOn().  My Nano is just connected to the USB of NB.
Any help were appreciated
Regards, Gena
